---
title: "Household Pulse Education 6"
output: html_document
---

#STORE DATA IN SQL DATABASE: education6

## This code simply imports the data from Education Table 6, and calculates a nonresponse percent.


```{r}
library(tidyverse)
library(readxl)
library(httr)
library(stringr)
```

## STEP 1: UPDATE THE MOST RECENT WEEK FOR DOWNLOADING DATA
```{r}
week <- 24
state_abbr <- 'SD'
```

## STEP 2: IMPORT MOST RECENT WEEK OF DATA
```{r}
#Parent directory by week: https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/

#Education table 6 column names
education6_colnames <-
  c("select_characteristics", "total", "no_change", "canceled", "different_format", "fewer_classes", "more_classes", "different_institution", "different_degree", "did_not_report")
categorynames <- c('total','age','age','age','age','age',
                          'sex','sex',
                          'race','race','race','race','race',
                          'education','education','education','education',
                          'maritalstatus','maritalstatus','maritalstatus',
                          'maritalstatus','maritalstatus',
                          'householdsize','householdsize','householdsize',
                          'householdsize','householdsize','householdsize',
                          'householdsize',
                          'children','children',
                          'income','income','income','income','income','income',
                          'income','income','income',
                          'spending','spending','spending','spending','spending',
                          'spending','spending','spending','spending')

#Import from Census parent directory
temp.file <- paste(tempfile(),".xlsx",sep = "")
download.file(paste0
                ("https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/wk",week,"/educ6_week",week,".xlsx"), 
                temp.file, mode = "wb")

education6_data <- read_excel(temp.file, sheet=paste0(state_abbr),skip = 4) %>%
    set_names(education6_colnames) %>%
  
  #remove extra rows at beginning and end
    subset(!is.na(select_characteristics)) %>%
    filter(!str_detect(select_characteristics, "Totals may not sum")) %>%
    filter(!str_detect(select_characteristics, "The Census Bureau considers")) %>%
    filter(!str_detect(select_characteristics, "Select characteristics")) %>%
  
  #remove row headers, but then add back in category name
    subset(!is.na(total)) %>%
    add_column(categorynames) %>%
  
  #assign dashes to NA
    na_if("-") %>%
  
  #convert numeric variables to numeric
    mutate_at(vars(total,no_change,canceled,different_format,fewer_classes,more_classes,different_institution,different_degree,did_not_report),
              list(~ as.numeric(.))) %>%
  
  #add in variable for week and state
  mutate(week=all_of(week)) %>%
  mutate(state=all_of(state_abbr)) %>%
  
  #calculate numerator, denominator for usually/always have computer and internet
  rowwise() %>%
  #calculate non-response rate for good measure
  mutate(nonresponse_percent=did_not_report/total)

##DATA QUALITY CHECKS
View(education6_data)

```

## STEP 3: IMPORT AND ADD STANDARD ERROR
```{r}
#Parent directory by week: https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/

#Education table 6 column names
education6_colnames <-
  c("select_characteristics", "total", "no_change", "canceled", "different_format", "fewer_classes", "more_classes", "different_institution", "different_degree", "did_not_report")
categorynames <- c('total','age','age','age','age','age',
                          'sex','sex',
                          'race','race','race','race','race',
                          'education','education','education','education',
                          'maritalstatus','maritalstatus','maritalstatus',
                          'maritalstatus','maritalstatus',
                          'householdsize','householdsize','householdsize',
                          'householdsize','householdsize','householdsize',
                          'householdsize',
                          'children','children',
                          'income','income','income','income','income','income',
                          'income','income','income',
                          'spending','spending','spending','spending','spending',
                          'spending','spending','spending','spending')

#Import from Census parent directory
temp.file <- paste(tempfile(),".xlsx",sep = "")
download.file(paste0
                ("https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/wk",week,"/educ6_se_week",week,".xlsx"), 
                temp.file, mode = "wb")

education6_data_se <- read_excel(temp.file, sheet=paste0(state_abbr),skip = 4) %>%
    set_names(education6_colnames) %>%
  
  #remove extra rows at beginning and end
    subset(!is.na(select_characteristics)) %>%
    filter(!str_detect(select_characteristics, "Totals may not sum")) %>%
    filter(!str_detect(select_characteristics, "The Census Bureau considers")) %>%
    filter(!str_detect(select_characteristics, "Select characteristics")) %>%
  
  #remove row headers, but then add back in category name
    subset(!is.na(total)) %>%
    add_column(categorynames) %>%
  
  #assign dashes to na
    na_if("-") %>%
  
  #convert numeric variables to numeric
    mutate_at(vars(total,no_change,canceled,different_format,fewer_classes,more_classes,different_institution,different_degree,did_not_report),
              list(~ as.numeric(.))) %>%
  
  #convert NA's to zero
  replace(is.na(.),0) %>%
  
  #add in variable for week and state
  mutate(week=all_of(week)) %>%
  mutate(state=all_of(state_abbr)) %>%
  
  #change variable names to _se
  rename(total_se=total,
         no_change_se=no_change,
         canceled_se=canceled,
         different_format_se=different_format,
         fewer_classes_se=fewer_classes,
         more_classes_se=more_classes,
         different_institution_se=different_institution,
         different_degree_se=different_degree,
         did_not_report_se=did_not_report) 
           
  

##DATA QUALITY CHECKS
View(education6_data_se)

```

## STEP 4: COMBINE DATA AND STANDARD ERROR
```{r}
education6_datacombined <- education6_data %>%
  left_join(education6_data_se,by=c('select_characteristics'='select_characteristics',
                             'week'='week','categorynames'='categorynames',
                             'state'='state'))

##DATA QUALITY CHECKS
View(education6_datacombined)
```

## STEP 5: ADD MOST RECENT WEEK DATA TO SQL DATABASE
```{r}
dbWriteTable(con,'education6',education6_datacombined,append=TRUE,row.names=FALSE)
```


