---
title: "Household Pulse Food 5"
output: html_document
---

#STARTING IN WEEK 22, THIS CODE WILL WORK
#IMPORT HOUSEHOLD PULSE DATA FROM TABLE FOOD 5
#STORE DATA IN SQL DATABASE: food5


```{r}
library(tidyverse)
library(readxl)
library(httr)
library(stringr)
```

## STEP 1: UPDATE THE MOST RECENT WEEK FOR DOWNLOADING DATA
```{r}
week <- 27
state_abbr <- 'SD'
```

## STEP 2: IMPORT MOST RECENT WEEK OF DATA
```{r}
#Parent directory by week: https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/

#Food table 5 column names
food5_colnames <-
  c("select_characteristics", "total", "enough_not_types", "sometimes_not_enough", "often_not_enough", "did_not_report")
categorynames <- c('total',
                   'recentfoodinsufficiencyreason','recentfoodinsufficiencyreason',
                   'recentfoodinsufficiencyreason','recentfoodinsufficiencyreason',
                   'recentfoodinsufficiencyreason','recentfoodinsufficiencyreason',
                   'freegroceries','freegroceries','freegroceries',
                   'freegroceries_provider','freegroceries_provider',
                   'freegroceries_provider','freegroceries_provider',
                   'freegroceries_provider','freegroceries_provider',
                   'freegroceries_provider','freegroceries_provider',
                   'foodathome','foodathome',
                   'foodawayfromhome','foodawayfromhome',
                   'childrennoteating','childrennoteating',
                   'childrennoteating','childrennoteating',
                   'anxious','anxious','anxious','anxious','anxious',
                   'worry','worry','worry','worry','worry',
                   'nointerest','nointerest','nointerest','nointerest','nointerest',
                   'depressed','depressed','depressed','depressed','depressed',
                   'spending','spending','spending','spending','spending','spending',
                   'spending','spending','spending',
                   'snap','snap','snap')

#Import from Census parent directory
temp.file <- paste(tempfile(),".xlsx",sep = "")
download.file(paste0
                ("https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/wk",week,"/food5_week",week,".xlsx"), 
                temp.file, mode = "wb")

food5_data <- read_excel(temp.file, sheet=paste0(state_abbr),skip = 5) %>%
    set_names(food5_colnames) %>%
  
  #remove extra rows at beginning and end
    subset(!is.na(select_characteristics)) %>%
    filter(!str_detect(select_characteristics, "Totals may not sum")) %>%
    filter(!str_detect(select_characteristics, "The Census Bureau considers")) %>%
    filter(!str_detect(select_characteristics, "Select characteristics")) %>%
  
  #remove row headers, but then add back in category name
    subset(!is.na(total)) %>%
    add_column(categorynames) %>%
  
  #assign dashes to NA
    na_if("-") %>%
  
  #convert numeric variables to numeric
    mutate_at(vars(total,enough_not_types,
                   sometimes_not_enough,often_not_enough,did_not_report),
              list(~ as.numeric(.))) %>%
  
  #add in variable for week and state
  mutate(week=all_of(week)) %>%
  mutate(state=all_of(state_abbr)) %>%
  
  #calculate numerator, denominator and percentage for food insufficient = (sometimes+often)/(valid responses) %>%
  rowwise() %>%
  #calculate non-response rate for good measure
  mutate(nonresponse_percent=did_not_report/total)

##DATA QUALITY CHECKS
View(food5_data)

```

## STEP 3: IMPORT AND ADD STANDARD ERROR
```{r}
#Parent directory by week: https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/

#Food table 5 column names
food5_colnames <-
  c("select_characteristics", "total", "enough_not_types", "sometimes_not_enough", "often_not_enough", "did_not_report")
categorynames <- c('total',
                   'recentfoodinsufficiencyreason','recentfoodinsufficiencyreason',
                   'recentfoodinsufficiencyreason','recentfoodinsufficiencyreason',
                   'recentfoodinsufficiencyreason','recentfoodinsufficiencyreason',
                   'freegroceries','freegroceries','freegroceries',
                   'freegroceries_provider','freegroceries_provider',
                   'freegroceries_provider','freegroceries_provider',
                   'freegroceries_provider','freegroceries_provider',
                   'freegroceries_provider','freegroceries_provider',
                   'foodathome','foodathome',
                   'foodawayfromhome','foodawayfromhome',
                   'childrennoteating','childrennoteating',
                   'childrennoteating','childrennoteating',
                   'anxious','anxious','anxious','anxious','anxious',
                   'worry','worry','worry','worry','worry',
                   'nointerest','nointerest','nointerest','nointerest','nointerest',
                   'depressed','depressed','depressed','depressed','depressed',
                   'spending','spending','spending','spending','spending','spending',
                   'spending','spending','spending',
                   'snap','snap','snap')

#Import from Census parent directory
temp.file <- paste(tempfile(),".xlsx",sep = "")
download.file(paste0
                ("https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/wk",week,"/food5_se_week",week,".xlsx"), 
                temp.file, mode = "wb")

food5_data_se <- read_excel(temp.file, sheet=paste0(state_abbr),skip = 5) %>%
    set_names(food5_colnames) %>%
  
  #remove extra rows at beginning and end
    subset(!is.na(select_characteristics)) %>%
    filter(!str_detect(select_characteristics, "Totals may not sum")) %>%
    filter(!str_detect(select_characteristics, "The Census Bureau considers")) %>%
    filter(!str_detect(select_characteristics, "Select characteristics")) %>%
  
  #remove row headers, but then add back in category name
    subset(!is.na(total)) %>%
    add_column(categorynames) %>%
  
  #assign dashes to na
    na_if("-") %>%
  
  #convert numeric variables to numeric
    mutate_at(vars(total,enough_not_types,
                   sometimes_not_enough,often_not_enough,did_not_report),
              list(~ as.numeric(.))) %>%
  
  #convert NA's to zero
  replace(is.na(.),0) %>%
  
  #add in variable for week and state
  mutate(week=all_of(week)) %>%
  mutate(state=all_of(state_abbr)) %>%
  
  #change variable names to _se
  rename(total_se=total,
         enough_not_types_se=enough_not_types,
         sometimes_not_enough_se=sometimes_not_enough,
         often_not_enough_se=often_not_enough,
         did_not_report_se=did_not_report) 

##DATA QUALITY CHECKS
View(food5_data_se)

```

## STEP 4: COMBINE DATA AND STANDARD ERROR
```{r}
food5_datacombined <- food5_data %>%
  left_join(food5_data_se,by=c('select_characteristics'='select_characteristics',
                             'week'='week','categorynames'='categorynames',
                             'state'='state'))

##DATA QUALITY CHECKS
View(food5_datacombined)
```

## STEP 5: ADD MOST RECENT WEEK DATA TO SQL DATABASE
```{r}
dbWriteTable(con,'food5',food5_datacombined,append=TRUE,row.names=FALSE)
```

