---
title: "Household Pulse Food 3B"
output: html_document
---

#THIS CODE WORKS FOR WEEKS 7-12
#IMPORT HOUSEHOLD PULSE DATA FROM TABLE FOOD 3B
#STORE DATA IN SQL DATABASE: food3b


```{r}
library(tidyverse)
library(readxl)
library(httr)
library(stringr)
```

## STEP 1: UPDATE THE MOST RECENT WEEK FOR DOWNLOADING DATA
```{r}
week <- 12
state_abbr <- 'SD'
```

## STEP 2: IMPORT MOST RECENT WEEK OF DATA
```{r}
#Parent directory by week: https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/

#Food table 3b column names
food3b_colnames <-
  c("select_characteristics", "total", "enough_types_food", "enough_not_types", "sometimes_not_enough", "often_not_enough", "did_not_report")
categorynames <- c('total','age','age','age','age','age',
                          'sex','sex',
                          'race','race','race','race','race',
                          'education','education','education','education',
                          'maritalstatus','maritalstatus','maritalstatus',
                          'maritalstatus','maritalstatus',
                          'householdsize','householdsize','householdsize',
                          'householdsize','householdsize','householdsize',
                          'householdsize',
                          'lossincome',
                          'lossincome','lossincome',
                          'currentemploy','currentemploy',
                          'currentemploy','notworkreason','notworkreason',
                          'notworkreason','notworkreason','notworkreason',
                          'notworkreason','notworkreason','notworkreason',
                          'notworkreason','notworkreason','notworkreason',
                          'notworkreason','notworkreason','receivepay',
                          'receivepay','receivepay','receivepay','receivepay',
                          'income','income','income','income','income','income',
                          'income','income','income',
                          'spending','spending','spending','spending','spending',
                          'spending','spending','spending',
                          'healthstatus','healthstatus','healthstatus',
                          'healthstatus',
                          'healthstatus','healthstatus',
                          'anxious','anxious','anxious',
                          'anxious','anxious','worry','worry','worry',
                          'worry','worry',
                          'nointerest','nointerest','nointerest','nointerest',
                          'nointerest','depressed',
                          'depressed','depressed','depressed',
                          'depressed','healthinsurance','healthinsurance',
                          'healthinsurance','lastrent','lastrent',
                          'lastrent','lastrent','lastrent',
                          'nextrent','nextrent','nextrent',
                          'nextrent',
                          'nextrent','nextrent','freegroceries','freegroceries',
                          'freegroceries','freegroceries_provider',
                          'freegroceries_provider','freegroceries_provider',
                          'freegroceries_provider','freegroceries_provider',
                          'freegroceries_provider','freegroceries_provider',
                          'freegroceries_provider')

#Import from Census parent directory
temp.file <- paste(tempfile(),".xlsx",sep = "")
download.file(paste0
                ("https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/wk",week,"/food3b_week",week,".xlsx"), 
                temp.file, mode = "wb")

food3b_data <- read_excel(temp.file, sheet=paste0(state_abbr),skip = 4) %>%
    set_names(food3b_colnames) %>%
  
  #remove extra rows at beginning and end
    subset(!is.na(select_characteristics)) %>%
    filter(!str_detect(select_characteristics, "Totals may not sum")) %>%
    filter(!str_detect(select_characteristics, "The Census Bureau considers")) %>%
    filter(!str_detect(select_characteristics, "Select characteristics")) %>%
  
  #remove row headers, but then add back in category name
    subset(!is.na(total)) %>%
    add_column(categorynames) %>%
  
  #assign dashes to NA
    na_if("-") %>%
  
  #convert numeric variables to numeric
    mutate_at(vars(total,enough_types_food,enough_not_types,
                   sometimes_not_enough,often_not_enough,did_not_report),
              list(~ as.numeric(.))) %>%
  
  #add in variable for week and state
  mutate(week=all_of(week)) %>%
  mutate(state=all_of(state_abbr)) %>%
  
  #calculate numerator, denominator and percentage for food insufficient = (sometimes+often)/(valid responses) %>%
  rowwise() %>%
  mutate(foodinsufficient_numerator=sum(sometimes_not_enough,often_not_enough,na.rm=TRUE),
         totalvalidresponses=sum(enough_types_food,enough_not_types,
           sometimes_not_enough,often_not_enough,na.rm=TRUE)) %>%
  #calculate non-response rate for good measure
  mutate(nonresponse_percent=did_not_report/total)

##DATA QUALITY CHECKS
View(food3b_data)

```

## STEP 3: IMPORT AND ADD STANDARD ERROR
```{r}
#Parent directory by week: https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/

#Food table 3b column names
food3b_colnames <-
  c("select_characteristics", "total", "enough_types_food", "enough_not_types", "sometimes_not_enough", "often_not_enough", "did_not_report")
categorynames <- c('total','age','age','age','age','age',
                          'sex','sex',
                          'race','race','race','race','race',
                          'education','education','education','education',
                          'maritalstatus','maritalstatus','maritalstatus',
                          'maritalstatus','maritalstatus',
                          'householdsize','householdsize','householdsize',
                          'householdsize','householdsize','householdsize',
                          'householdsize',
                          'lossincome',
                          'lossincome','lossincome',
                          'currentemploy','currentemploy',
                          'currentemploy','notworkreason','notworkreason',
                          'notworkreason','notworkreason','notworkreason',
                          'notworkreason','notworkreason','notworkreason',
                          'notworkreason','notworkreason','notworkreason',
                          'notworkreason','notworkreason','receivepay',
                          'receivepay','receivepay','receivepay','receivepay',
                          'income','income','income','income','income','income',
                          'income','income','income',
                          'spending','spending','spending','spending','spending',
                          'spending','spending','spending',
                          'healthstatus','healthstatus','healthstatus',
                          'healthstatus',
                          'healthstatus','healthstatus',
                          'anxious','anxious','anxious',
                          'anxious','anxious','worry','worry','worry',
                          'worry','worry',
                          'nointerest','nointerest','nointerest','nointerest',
                          'nointerest','depressed',
                          'depressed','depressed','depressed',
                          'depressed','healthinsurance','healthinsurance',
                          'healthinsurance','lastrent','lastrent',
                          'lastrent','lastrent','lastrent',
                          'nextrent','nextrent','nextrent',
                          'nextrent',
                          'nextrent','nextrent','freegroceries','freegroceries',
                          'freegroceries','freegroceries_provider',
                          'freegroceries_provider','freegroceries_provider',
                          'freegroceries_provider','freegroceries_provider',
                          'freegroceries_provider','freegroceries_provider',
                          'freegroceries_provider')

#Import from Census parent directory
temp.file <- paste(tempfile(),".xlsx",sep = "")
download.file(paste0
                ("https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/wk",week,"/food3b_se_week",week,".xlsx"), 
                temp.file, mode = "wb")

food3b_data_se <- read_excel(temp.file, sheet=paste0(state_abbr),skip = 4) %>%
    set_names(food3b_colnames) %>%
  
  #remove extra rows at beginning and end
    subset(!is.na(select_characteristics)) %>%
    filter(!str_detect(select_characteristics, "Totals may not sum")) %>%
    filter(!str_detect(select_characteristics, "The Census Bureau considers")) %>%
    filter(!str_detect(select_characteristics, "Select characteristics")) %>%
  
  #remove row headers, but then add back in category name
    subset(!is.na(total)) %>%
    add_column(categorynames) %>%
  
  #assign dashes to na
    na_if("-") %>%
  
  #convert numeric variables to numeric
    mutate_at(vars(total,enough_types_food,enough_not_types,
                   sometimes_not_enough,often_not_enough,did_not_report),
              list(~ as.numeric(.))) %>%
  
  #convert NA's to zero
  replace(is.na(.),0) %>%
  
  #add in variable for week and state
  mutate(week=all_of(week)) %>%
  mutate(state=all_of(state_abbr)) %>%
  
  #change variable names to _se
  rename(total_se=total,
         enough_types_food_se=enough_types_food,
         enough_not_types_se=enough_not_types,
         sometimes_not_enough_se=sometimes_not_enough,
         often_not_enough_se=often_not_enough,
         did_not_report_se=did_not_report) %>%
  
  #calculate numerator, denominator and percentage for food insufficient = (sometimes+often)/(valid responses)
  mutate(foodinsufficient_numerator_se=sqrt((sometimes_not_enough_se^2)+(often_not_enough_se^2)),
         totalvalidresponses_se=sqrt((enough_types_food_se^2)+(enough_not_types_se^2)+
           (sometimes_not_enough_se^2)+(often_not_enough_se^2))) 

##DATA QUALITY CHECKS
View(food3b_data_se)

```

## STEP 4: COMBINE DATA AND STANDARD ERROR
```{r}
food3b_datacombined <- food3b_data %>%
  left_join(food3b_data_se,by=c('select_characteristics'='select_characteristics',
                             'week'='week','categorynames'='categorynames',
                             'state'='state'))

##DATA QUALITY CHECKS
View(food3b_datacombined)
```

## STEP 5: ADD MOST RECENT WEEK DATA TO SQL DATABASE
```{r}
dbWriteTable(con,'food3b',food3b_datacombined,append=TRUE,row.names=FALSE)
```

